billingAddressCondition:
  class: craft\commerce\elements\conditions\addresses\GatewayAddressCondition
  elementType: null
  fieldContext: global
handle: ozow
isFrontendEnabled: false
name: Ozow
orderCondition:
  class: craft\commerce\elements\conditions\orders\GatewayOrderCondition
  elementType: craft\commerce\elements\Order
  fieldContext: global
paymentType: purchase
shippingAddressCondition:
  class: craft\commerce\elements\conditions\addresses\GatewayAddressCondition
  elementType: null
  fieldContext: global
sortOrder: 99
type: modules\localroots\gateways\OzowGateway
