billingAddressCondition:
  class: craft\commerce\elements\conditions\addresses\GatewayAddressCondition
  elementType: null
  fieldContext: global
handle: payfast
isFrontendEnabled: '0'
name: PayFast
orderCondition:
  class: craft\commerce\elements\conditions\orders\GatewayOrderCondition
  elementType: craft\commerce\elements\Order
  fieldContext: global
paymentType: purchase
shippingAddressCondition:
  class: craft\commerce\elements\conditions\addresses\GatewayAddressCondition
  elementType: null
  fieldContext: global
sortOrder: 99
type: modules\localroots\gateways\PayfastGateway
