allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  66bb3209-65ce-4f01-a40a-208b72bfed2e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 69708747-71a3-4af3-9441-27f826fd5b2e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 462ba2ec-8fa1-4f29-82ff-c740590fd07d # Body
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd756cf0-6f47-4bbe-a288-d61004568696
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 42be12d0-3e9b-4127-b7bc-f5a399d0ee68
        userCondition: null
    thumbFieldKey: null
handle: orderStatus
hasTitleField: true
icon: null
name: 'Order Status'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
