allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  eceb5d22-ecdf-4758-8e1b-0840073f8a35:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 11e0473d-9816-4d6d-800c-6045a19e2619
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: be035570-dd96-4f29-af3d-40dd03989f7f # Hero Image
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ded752ca-6543-4af8-916e-318cc2cd4898
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 462ba2ec-8fa1-4f29-82ff-c740590fd07d # Body
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c749aa6c-1836-47ef-9a06-4382069b9d6f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e2fabbfd-bb9e-4e3c-924d-7f786ca408f3
        userCondition: null
    thumbFieldKey: null
handle: press
hasTitleField: true
icon: null
name: Press
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
