allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  58e920d7-7d3b-4930-93cd-d9ec0b9c9f47:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 093e61a8-a802-46ef-88fd-a5183b243054
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f10a395c-55d0-4395-a837-de7ef2b1a5e7 # Question
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22844b10-91bb-486a-a74f-ea1b575c0245
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 110b0bcf-f08d-4412-a6b5-d6d970d31124 # Answer
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec4375e9-8bc2-458c-aaa0-b35101abc3b5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 31fe6892-e89d-47bf-9288-fa9d81bab7e4 # Product
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6710185-792e-4087-9424-13d6a4534ba6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4055e381-b1f4-4996-9d07-a9c7d2b5761c # Author Name
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d233a16b-9c50-4757-b0be-a08086a73eeb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5d16cef5-02fa-44d6-bd34-95cef356c020 # Author Email
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4c247de-56d9-4c71-b6ea-0334740da009
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ee24c520-aefa-4e0e-b5b9-b4eb6946f93c # Question Status
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce836757-886e-4dcd-8cae-a592c64bbbee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bd4c08b5-7ee8-452f-9388-92e071c9e69c
        userCondition: null
    thumbFieldKey: null
handle: productQuestions
hasTitleField: true
icon: null
name: 'Product Questions'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
