defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: bc98ea82-68eb-48a3-9029-4005f46a5c7e # Press
handle: press
maxAuthors: 1
minAuthors: 1
name: Press
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  e510b8b9-def2-4e3c-b643-8da4bc86bdc1: # Local Roots Africa
    enabledByDefault: true
    hasUrls: true
    template: _pages/press/_entry
    uriFormat: 'press/{slug}'
type: channel
