defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: fd5c3c99-dda4-42bb-aaa8-d5b15dbb74da # Product Reviews
handle: productReviews
maxAuthors: 1
minAuthors: 1
name: 'Product Reviews'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  e510b8b9-def2-4e3c-b643-8da4bc86bdc1: # Local Roots Africa
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
